[style.description]
underline = false
bold = false
italic = false

# below is my home made dracula theme

[style.command_name]
foreground = {rgb = { r = 189, g = 147, b = 249 } } # purple
underline = false
bold = false
italic = false

[style.example_text]
foreground = { rgb = { r = 98, g = 114, b = 164 } } # comment
underline = false
bold = false
italic = false

[style.example_code]
foreground = { rgb = { r = 255, g = 184, b = 108 } } # orange
underline = false
bold = false
italic = false

[style.example_variable]
foreground = { rgb = { r = 80, g = 250, b = 123 } } # green
underline = false
bold = false
italic = true

[display]
compact = false
use_pager = true

[updates]
auto_update = true
auto_update_interval_hours = 720

[directories]
