[style.description]
underline = false
bold = false
italic = false

# below is my home made dracula theme

[style.command_name]
foreground = { ansi = 183 } # purple
underline = false
bold = false
italic = false

[style.example_text]
foreground = { ansi = 103 } # comment
underline = false
bold = false
italic = false

[style.example_code]
foreground = { ansi = 222 } # orange
underline = false
bold = false
italic = false

[style.example_variable]
foreground = { ansi = 120 } # green
underline = false
bold = false
italic = true

[display]
compact = false
use_pager = true

[updates]
auto_update = true
auto_update_interval_hours = 720

[directories]
