gui:
  skipDiscardChangeWarning: true
  skipStashWarning: true
  nerdFontsVersion: "3"
  theme:
    selectedLineBgColor:
      - bold
      - underline
      # - reverse
git:
  branchLogCmd: "git log --graph {{branchName}} --"
  paging:
    colorArg: always
    pager: delta --true-color never --paging=never
  allBranchesLogCmds:
    - git log --graph --all
refresher:
  refreshInterval: 2 # file/submodule refresh interval in seconds
  fetchInterval: 300 # re-fetch interval in seconds
notARepository: "skip"
promptToReturnFromSubprocess: false
keybinding:
  files:
    toggleTreeView: "รถ" # default is ` which is undetectable`
quitOnTopLevelReturn: true
