prSections:
  - title: My Pull Requests
    filters: is:open author:@me repo:dmazeio/frontend
  - title: Needs My Review
    filters: is:open review-requested:@me repo:dmazeio/frontend
  - title: Involved
    filters: is:open involves:@me -author:@me repo:dmazeio/frontend
issuesSections:
  - title: My Issues
    filters: is:open author:@me repo:dmazeio/frontend
  - title: Assigned
    filters: is:open assignee:@me repo:dmazeio/frontend
  - title: Involved
    filters: is:open involves:@me -author:@me repo:dmazeio/frontend
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: []
repoPaths:
  :owner/:repo: ~/code/experiments/gh-dash/:owner/:repo # template if you always clone github repos in a consistent location
pager:
  diff: delta
