#!/usr/bin/env zsh
yb() {
    local logfile
    if [[ -n $UNAME_MACOS ]]; then
        logfile=$HOME/Library/Logs/yadm_log
    else
        logfile=${XDG_STATE_HOME:-~/.cache}/yadm_log
    fi

    # check if I already have sudo rights
    if ! sudo -n true 2>/dev/null; then
        # if not, request sudo login right away
        sudo -v
    fi &&
       if [[ -n $UNAME_MACOS ]]; then
        (echo "\n$(date -u +%F\ %T)" &&
        script -q /dev/null yadm pull &&
            [[ "$(yadm --version)" == "yadm 3"* ]] &&
            script -q /dev/null yadm bootstrap ||
            script -q /dev/null $HOME/.config/yadm/bootstrap &&
            script -q /dev/null ~/.config/yadm/bootstrap-sudo &&
            script -q /dev/null yadm push) 2>&1 | tee -a $logfile
       else
         echo "\n$(date -u +%F\ %T)" >> $logfile &&
         script -qefa $logfile -c 'yadm pull' &&
            [[ "$(yadm --version)" == "yadm 3"* ]] &&
            script -qefa $logfile -c "yadm bootstrap" ||
            script -qefa $logfile -c "$HOME/.config/yadm/bootstrap" &&
            script -qefa $logfile -c "$HOME/.config/yadm/bootstrap-sudo" &&
            script -qefa $logfile -c "yadm push"
       fi
}
yb "$@"
