#!/bin/bash
# stop startup sound
sudo nvram SystemAudioVolume=%80
# Add Watch Simulator to Launchpad
sudo ln -sf "/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app" "/Applications/Simulator.app"

###############################################################################
# installations for Klarna
###############################################################################
sudo gem install cocoapods --pre

###############################################################################
# bash4
###############################################################################
if ! grep -q "/usr/local/bin/bash" "/etc/shells"; then
   sudo sh -c 'echo /usr/local/bin/bash >> /etc/shells'
fi
# chsh -s /usr/local/bin/bash $SUDO_USER

###############################################################################
# fish
###############################################################################
if ! grep -q fish "/etc/shells"; then
   sudo sh -c 'echo /usr/local/bin/fish >> /etc/shells'
fi

###############################################################################
# zsh
###############################################################################
if ! grep -q "/usr/local/bin/zsh" "/etc/shells"; then
   sudo sh -c 'echo /usr/local/bin/zsh >> /etc/shells'
fi
chsh -s /usr/local/bin/zsh $SUDO_USER


###############################################################################
# Update App Store apps
###############################################################################
sudo softwareupdate -i -a